### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Pradyuman7** [Pradyuman7/Algorithmics#25]
- Make documentation more clear and easy to understand
- Add/improve code examples
- Make the Docs.md look better

**Comment by aaishikasb** [comment]
Hi, can I work on this?

**Comment by Pradyuman7** [comment]
Yes, please feel free to work on this @aaishikasb

**Comment by aaishikasb** [comment]
On it, in the meantime can you checkout #31 as well? Some amendments to the grammatical errors as well as a more readable approach.

**Comment by aaishikasb** [comment]
@Pradyuman7 please check out #32 which resolves the issue.
