### ISSUE TITLE
Update main ReadMe of the repository

### ISSUE THREAD

**Issue by Pradyuman7** [Pradyuman7/Algorithmics#6]
Update and add new styling options, gifs, images, extra information and all the stuff that can show your creativity and help making this repository look nicer.

**Comment by vidhik2002** [comment]
heyy @Pradyuman7 , could you assign me this issue?

**Comment by Pradyuman7** [comment]
Yes, please feel free to work on the issue, I shall make sure to review and merge your PR asap. I am not assigning the issue to anyone since many people can work on improving it and we can all share the issue number in the PRs.
